// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_generate_emoji from "./routes/api/generate-emoji.ts";
import * as $index from "./routes/index.tsx";
import * as $Disclosure from "./islands/Disclosure.tsx";
import * as $EmojiDisplay from "./islands/EmojiDisplay.tsx";
import * as $EmojiForm from "./islands/EmojiForm.tsx";
import * as $EmojiList from "./islands/EmojiList.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/generate-emoji.ts": $api_generate_emoji,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Disclosure.tsx": $Disclosure,
    "./islands/EmojiDisplay.tsx": $EmojiDisplay,
    "./islands/EmojiForm.tsx": $EmojiForm,
    "./islands/EmojiList.tsx": $EmojiList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
